from __future__ import unicode_literals

import logging
import json

from djangon.dispatch import receiver

from reviewboard.signals import initializing

class Integration(object):
    """ An interface to third-party services"""

    # unique id for each integration generated by path
    integration_id = None

    # Display name for integration
    name = None

    # allow single or multiple registration of this integration
    allows_localsites = False

    # flag for repositories usage
    supports_repositories = False

    needs_authentication = False

    icon_path = None

    form = None

    # Additional template to be render on integration page
    config_template = None

    def get_authentication_url(self):
        pass

    def __init__(self):
        # Take in dictionary from json fields in db
        # register_signal
        pass

    def shutdown(self):
        # shutdown_signal
        pass

_initialized = False
_enabled_integration = {}

# Keep track of all the integrations
_integrations = {} 

def register_integration():
    # TODO need take note of allow_localsite in registering
    pass

def shutdown_integration():
    # full shutdown
    pass

# Return the list of all integrations
def get_integrations():
    # TODO need to take note of allow_localsite for different user
    pass

# Initialize on startup
@recevier()
def _on_initializating(**kwargs):
    pass